package Interfaces;

import Modelo.Modelo_Proveedor;
import Modelo.Modelo_Empleado;
import Modelo.Modelo_Marca;
import Modelo.Modelo_Cliente;
import Modelo.Modelo_ProducProvee;
import Clases.*;
import Coneccion_BD.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Escritorio extends javax.swing.JFrame {

    public static Modelo_Empleado MTE = new Modelo_Empleado();
    public static Modelo_Cliente MTC = new Modelo_Cliente();
    public static Modelo_Marca MTM = new Modelo_Marca();
    public static Modelo_Proveedor MTP = new Modelo_Proveedor();
    public static Modelo_ProducProvee MTPP = new Modelo_ProducProvee();

    public Escritorio() throws Exception {
        initComponents();
        cargar_datos_Empleado();
        cargar_datos_Cliente();
        cargar_datos_Marca();
        cargar_datos_Proveedor();
        cargar_datos_Producto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpEscritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        RegistrarMenu = new javax.swing.JMenu();
        RegClienteMenuItem = new javax.swing.JMenuItem();
        RegEmpleadoMenuItem = new javax.swing.JMenuItem();
        RegMarcaMenuItem = new javax.swing.JMenuItem();
        RegProductoMenuItem = new javax.swing.JMenuItem();
        RegProveedMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        SalirMenuItem = new javax.swing.JMenuItem();
        EditarMenu = new javax.swing.JMenu();
        EditClieMenuItem = new javax.swing.JMenuItem();
        EditEmpleMenuItem = new javax.swing.JMenuItem();
        EditMarcaMenuItem = new javax.swing.JMenuItem();
        EditProdMenuItem = new javax.swing.JMenuItem();
        EditProveeMenuItem = new javax.swing.JMenuItem();
        GenerarMenu = new javax.swing.JMenu();
        PedidoMenuItem = new javax.swing.JMenuItem();
        VentaMenuItem = new javax.swing.JMenuItem();
        ReportesMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        ListadoMenu = new javax.swing.JMenu();
        ListClieMenuItem = new javax.swing.JMenuItem();
        ListEmplMenuItem = new javax.swing.JMenuItem();
        ListMarcMenuItem = new javax.swing.JMenuItem();
        ListProdMenuItem = new javax.swing.JMenuItem();
        ListProveeMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RegistrarMenu.setMnemonic('f');
        RegistrarMenu.setText("Registar");

        RegClienteMenuItem.setMnemonic('s');
        RegClienteMenuItem.setText("Cliente");
        RegClienteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegClienteMenuItemActionPerformed(evt);
            }
        });
        RegistrarMenu.add(RegClienteMenuItem);

        RegEmpleadoMenuItem.setMnemonic('o');
        RegEmpleadoMenuItem.setText("Empleado");
        RegEmpleadoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegEmpleadoMenuItemActionPerformed(evt);
            }
        });
        RegistrarMenu.add(RegEmpleadoMenuItem);

        RegMarcaMenuItem.setMnemonic('a');
        RegMarcaMenuItem.setText("Marca");
        RegMarcaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegMarcaMenuItemActionPerformed(evt);
            }
        });
        RegistrarMenu.add(RegMarcaMenuItem);

        RegProductoMenuItem.setText("Producto");
        RegProductoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegProductoMenuItemActionPerformed(evt);
            }
        });
        RegistrarMenu.add(RegProductoMenuItem);

        RegProveedMenuItem.setText("Proveedor");
        RegProveedMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegProveedMenuItemActionPerformed(evt);
            }
        });
        RegistrarMenu.add(RegProveedMenuItem);
        RegistrarMenu.add(jSeparator1);

        SalirMenuItem.setMnemonic('x');
        SalirMenuItem.setText("Salir");
        SalirMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirMenuItemActionPerformed(evt);
            }
        });
        RegistrarMenu.add(SalirMenuItem);

        menuBar.add(RegistrarMenu);

        EditarMenu.setMnemonic('e');
        EditarMenu.setText("Editar");

        EditClieMenuItem.setMnemonic('y');
        EditClieMenuItem.setText("Cliente");
        EditClieMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditClieMenuItemActionPerformed(evt);
            }
        });
        EditarMenu.add(EditClieMenuItem);

        EditEmpleMenuItem.setMnemonic('t');
        EditEmpleMenuItem.setText("Empleado");
        EditEmpleMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditEmpleMenuItemActionPerformed(evt);
            }
        });
        EditarMenu.add(EditEmpleMenuItem);

        EditMarcaMenuItem.setText("Marca");
        EditMarcaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditMarcaMenuItemActionPerformed(evt);
            }
        });
        EditarMenu.add(EditMarcaMenuItem);

        EditProdMenuItem.setMnemonic('p');
        EditProdMenuItem.setText("Producto");
        EditProdMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProdMenuItemActionPerformed(evt);
            }
        });
        EditarMenu.add(EditProdMenuItem);

        EditProveeMenuItem.setMnemonic('d');
        EditProveeMenuItem.setText("Proveedor");
        EditProveeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProveeMenuItemActionPerformed(evt);
            }
        });
        EditarMenu.add(EditProveeMenuItem);

        menuBar.add(EditarMenu);

        GenerarMenu.setMnemonic('h');
        GenerarMenu.setText("Generar...");

        PedidoMenuItem.setText("Pedido");
        PedidoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidoMenuItemActionPerformed(evt);
            }
        });
        GenerarMenu.add(PedidoMenuItem);

        VentaMenuItem.setText("Venta");
        VentaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentaMenuItemActionPerformed(evt);
            }
        });
        GenerarMenu.add(VentaMenuItem);

        menuBar.add(GenerarMenu);

        ReportesMenu.setBackground(new java.awt.Color(0, 204, 204));
        ReportesMenu.setText("Reportes");

        jMenuItem1.setText("Total Compras");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        ReportesMenu.add(jMenuItem1);

        menuBar.add(ReportesMenu);

        ListadoMenu.setText("Listados");

        ListClieMenuItem.setText("Lista Cliente");
        ListClieMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListClieMenuItemActionPerformed(evt);
            }
        });
        ListadoMenu.add(ListClieMenuItem);

        ListEmplMenuItem.setText("Lista Empleado");
        ListEmplMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListEmplMenuItemActionPerformed(evt);
            }
        });
        ListadoMenu.add(ListEmplMenuItem);

        ListMarcMenuItem.setText("Lista Marca");
        ListMarcMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListMarcMenuItemActionPerformed(evt);
            }
        });
        ListadoMenu.add(ListMarcMenuItem);

        ListProdMenuItem.setText("Lista Producto");
        ListProdMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListProdMenuItemActionPerformed(evt);
            }
        });
        ListadoMenu.add(ListProdMenuItem);

        ListProveeMenuItem.setText("Lista Proveedor");
        ListProveeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListProveeMenuItemActionPerformed(evt);
            }
        });
        ListadoMenu.add(ListProveeMenuItem);

        menuBar.add(ListadoMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirMenuItemActionPerformed

    private void RegEmpleadoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegEmpleadoMenuItemActionPerformed
        IFRegistraEmpleado emp = new IFRegistraEmpleado();
        this.dpEscritorio.add(emp);
        emp.setVisible(true);
    }//GEN-LAST:event_RegEmpleadoMenuItemActionPerformed

    private void RegClienteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegClienteMenuItemActionPerformed
        IFRegistroCliente clie = new IFRegistroCliente();
        this.dpEscritorio.add(clie);
        clie.setVisible(true);
    }//GEN-LAST:event_RegClienteMenuItemActionPerformed

    private void ListEmplMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListEmplMenuItemActionPerformed
        IFListaEmplead intf = new IFListaEmplead();
        this.dpEscritorio.add(intf);
        intf.setVisible(true);
    }//GEN-LAST:event_ListEmplMenuItemActionPerformed

    private void ListClieMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListClieMenuItemActionPerformed
        IFListaCliente rep = new IFListaCliente();
        this.dpEscritorio.add(rep);
        rep.setVisible(true);
    }//GEN-LAST:event_ListClieMenuItemActionPerformed

    private void ListMarcMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListMarcMenuItemActionPerformed
        IFListaMarca rep = new IFListaMarca();
        this.dpEscritorio.add(rep);
        rep.setVisible(true);
    }//GEN-LAST:event_ListMarcMenuItemActionPerformed

    private void RegMarcaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegMarcaMenuItemActionPerformed
        IFRegistroMarca mar = new IFRegistroMarca();
        this.dpEscritorio.add(mar);
        mar.setVisible(true);
    }//GEN-LAST:event_RegMarcaMenuItemActionPerformed

    private void ListProveeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListProveeMenuItemActionPerformed
        IFListaProveedor pro = new IFListaProveedor();
        this.dpEscritorio.add(pro);
        pro.setVisible(true);
    }//GEN-LAST:event_ListProveeMenuItemActionPerformed

    private void RegProveedMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegProveedMenuItemActionPerformed
        IFRegistroProveed prove = new IFRegistroProveed();
        this.dpEscritorio.add(prove);
        prove.setVisible(true);
    }//GEN-LAST:event_RegProveedMenuItemActionPerformed

    private void RegProductoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegProductoMenuItemActionPerformed
        IFRegistroProducto prod = new IFRegistroProducto();
        this.dpEscritorio.add(prod);
        prod.setVisible(true);
    }//GEN-LAST:event_RegProductoMenuItemActionPerformed

    private void EditMarcaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditMarcaMenuItemActionPerformed
        IFEditarMarca edit = new IFEditarMarca();
        this.dpEscritorio.add(edit);
        edit.setVisible(true);
    }//GEN-LAST:event_EditMarcaMenuItemActionPerformed

    private void EditClieMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditClieMenuItemActionPerformed
        IFEditarClietne edit = new IFEditarClietne();
        this.dpEscritorio.add(edit);
        edit.setVisible(true);
    }//GEN-LAST:event_EditClieMenuItemActionPerformed

    private void EditProveeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProveeMenuItemActionPerformed
        IFEditarProveed edit = new IFEditarProveed();
        this.dpEscritorio.add(edit);
        edit.setVisible(true);
    }//GEN-LAST:event_EditProveeMenuItemActionPerformed

    private void EditEmpleMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditEmpleMenuItemActionPerformed
        IFEditarEmplead edit = new IFEditarEmplead();
        this.dpEscritorio.add(edit);
        edit.setVisible(true);
    }//GEN-LAST:event_EditEmpleMenuItemActionPerformed

    private void ListProdMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListProdMenuItemActionPerformed
        IFListaProducProvee list = new IFListaProducProvee();
        this.dpEscritorio.add(list);
        list.setVisible(true);
    }//GEN-LAST:event_ListProdMenuItemActionPerformed

    private void EditProdMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProdMenuItemActionPerformed
        IFEditarProducto edit = new IFEditarProducto();
        this.dpEscritorio.add(edit);
        edit.setVisible(true);
    }//GEN-LAST:event_EditProdMenuItemActionPerformed

    private void PedidoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidoMenuItemActionPerformed
        IFOrdenPedido ord = new IFOrdenPedido();
        this.dpEscritorio.add(ord);
        ord.setVisible(true);
    }//GEN-LAST:event_PedidoMenuItemActionPerformed

    private void VentaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentaMenuItemActionPerformed
        IFVenta vent = new IFVenta();
        this.dpEscritorio.add(vent);
        vent.setVisible(true);
    }//GEN-LAST:event_VentaMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        IFResporteClient rep = new IFResporteClient();
        this.dpEscritorio.add(rep);
        rep.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Escritorio().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Escritorio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EditClieMenuItem;
    private javax.swing.JMenuItem EditEmpleMenuItem;
    private javax.swing.JMenuItem EditMarcaMenuItem;
    private javax.swing.JMenuItem EditProdMenuItem;
    private javax.swing.JMenuItem EditProveeMenuItem;
    private javax.swing.JMenu EditarMenu;
    private javax.swing.JMenu GenerarMenu;
    private javax.swing.JMenuItem ListClieMenuItem;
    private javax.swing.JMenuItem ListEmplMenuItem;
    private javax.swing.JMenuItem ListMarcMenuItem;
    private javax.swing.JMenuItem ListProdMenuItem;
    private javax.swing.JMenuItem ListProveeMenuItem;
    private javax.swing.JMenu ListadoMenu;
    private javax.swing.JMenuItem PedidoMenuItem;
    private javax.swing.JMenuItem RegClienteMenuItem;
    private javax.swing.JMenuItem RegEmpleadoMenuItem;
    private javax.swing.JMenuItem RegMarcaMenuItem;
    private javax.swing.JMenuItem RegProductoMenuItem;
    private javax.swing.JMenuItem RegProveedMenuItem;
    private javax.swing.JMenu RegistrarMenu;
    private javax.swing.JMenu ReportesMenu;
    private javax.swing.JMenuItem SalirMenuItem;
    private javax.swing.JMenuItem VentaMenuItem;
    private javax.swing.JDesktopPane dpEscritorio;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

    static void cargar_datos_Empleado(){
        try {
            Llamado_BD llam = new Llamado_BD();
            ArrayList<Empleado> ltsEmpleado = llam.llenar_Empleado();
            Escritorio.MTE.setListado_Empleado(ltsEmpleado);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR!!!\n" + e.getMessage(), "Error BD", JOptionPane.ERROR_MESSAGE);
        }
    }

    static void cargar_datos_Cliente(){
        try {
            Llamado_BD llam = new Llamado_BD();
            ArrayList<Cliente> ltsCliente = llam.llenar_Cliente();
            Escritorio.MTC.setListado_Cliente(ltsCliente);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR!!!\n" + e.getMessage(), "Error BD", JOptionPane.ERROR_MESSAGE);
        }
    }

    static void cargar_datos_Marca(){
        try {
            Llamado_BD llam = new Llamado_BD();
            ArrayList<Marca> ltsMarca = llam.llenar_Marca();
            Escritorio.MTM.setListado_Marca(ltsMarca);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR!!!\n" + e.getMessage(), "Error BD", JOptionPane.ERROR_MESSAGE);
        }
    }

    static void cargar_datos_Proveedor(){
        try {
            Llamado_BD llam = new Llamado_BD();
            ArrayList<Proveedor> ltsProveedor = llam.llenar_Proveedor();
            Escritorio.MTP.setListado_Proveed(ltsProveedor);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR!!!\n" + e.getMessage(), "Error BD", JOptionPane.ERROR_MESSAGE);
        }
    }

    static void cargar_datos_Producto(){
        try {
            Llamado_BD llam = new Llamado_BD();
            ArrayList<Producto_Proveedor> ltsProProduc = llam.llenar_Producto_Provee();
            Escritorio.MTPP.setListado_ProdProvee(ltsProProduc);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR!!!\n" + e.getMessage(), "Error BD", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void dar_permiso(boolean estado, int opc) {
        //Opción 1: Habilitar para cajera
        //Opción 2: Habilitar para vendedor
        //opción 3: Habilitar para dueño
        this.EditEmpleMenuItem.setEnabled(!estado);
        this.RegEmpleadoMenuItem.setEnabled(!estado);
        this.ListadoMenu.setEnabled(!estado);
        switch (opc) {
            case 1:
                this.RegistrarMenu.setEnabled(!estado);
                this.EditarMenu.setEnabled(!estado);
                this.PedidoMenuItem.setEnabled(!estado);
                this.VentaMenuItem.setEnabled(estado);
                break;
            case 2:
                this.RegClienteMenuItem.setEnabled(estado);
                this.RegMarcaMenuItem.setEnabled(estado);
                this.RegProductoMenuItem.setEnabled(estado);
                this.RegProveedMenuItem.setEnabled(estado);
                this.EditClieMenuItem.setEnabled(estado);
                this.EditMarcaMenuItem.setEnabled(estado);
                this.EditProdMenuItem.setEnabled(estado);
                this.EditProveeMenuItem.setEnabled(estado);
                this.PedidoMenuItem.setEnabled(estado);
                this.VentaMenuItem.setEnabled(!estado);
                break;
            case 3:
                this.EditEmpleMenuItem.setEnabled(estado);
                this.RegEmpleadoMenuItem.setEnabled(estado);
                this.ListadoMenu.setEnabled(estado);
                this.RegistrarMenu.setEnabled(estado);
                this.EditarMenu.setEnabled(estado);
                this.GenerarMenu.setEnabled(estado);
                this.ReportesMenu.setEnabled(estado);
                break;
            default:
                break;
        }
    }
}
