package Interfaces;

import Clases.Empleado;
import Coneccion_BD.EditarBD;
import Modelo.Tamaño_TextField;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;

public class IFEditarEmplead extends javax.swing.JInternalFrame {

    private String sexo = "";
    private int telef = 0;
    private Empleado objE = null;

    public IFEditarEmplead() {
        initComponents();
        this.validar_tamañoTexto();
        this.definir_tamaño_columna();
        this.activar_controles(false);
        this.cargar_combo_cargo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldTelef1 = new javax.swing.JTextField();
        jTextFieldTelef3 = new javax.swing.JTextField();
        jTextFieldDirecc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jTextFieldDni = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldTelef2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jbtActualizar = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();
        jComboBoxHorario = new javax.swing.JComboBox<>();
        jComboBoxCargo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jbtBuscar = new javax.swing.JButton();
        jbtEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmplead = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Editar Empleado");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Nombres:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellidos:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DNI:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Teléfono:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dirección:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sexo:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Horario:");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cargo:");

        jTextFieldTelef1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldTelef1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelef1KeyTyped(evt);
            }
        });

        jTextFieldTelef3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldTelef3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelef3KeyTyped(evt);
            }
        });

        jTextFieldDirecc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel9.setText("-");

        jComboBoxSexo.setBackground(new java.awt.Color(51, 0, 51));
        jComboBoxSexo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-", "Femenino", "Masculino" }));

        jTextFieldDni.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDniKeyTyped(evt);
            }
        });

        jTextFieldNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyTyped(evt);
            }
        });

        jTextFieldTelef2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldTelef2.setToolTipText("");
        jTextFieldTelef2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelef2KeyTyped(evt);
            }
        });

        jLabel10.setText("-");

        jTextFieldApellido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldApellidoKeyTyped(evt);
            }
        });

        jbtActualizar.setBackground(new java.awt.Color(0, 0, 0));
        jbtActualizar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtActualizar.setForeground(java.awt.Color.white);
        jbtActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        jbtActualizar.setText("Actualizar");
        jbtActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtActualizarActionPerformed(evt);
            }
        });

        jbtCancelar.setBackground(java.awt.Color.red);
        jbtCancelar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtCancelar.setForeground(java.awt.Color.white);
        jbtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        jbtCancelar.setText("Cancelar");
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });

        jComboBoxHorario.setBackground(new java.awt.Color(51, 0, 51));
        jComboBoxHorario.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jComboBoxHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-", "8hr", "4hr" }));
        jComboBoxHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxHorarioActionPerformed(evt);
            }
        });

        jComboBoxCargo.setBackground(new java.awt.Color(51, 0, 51));
        jComboBoxCargo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel3))
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldDirecc, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldDni, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldApellido, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jTextFieldTelef1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldTelef2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldTelef3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBoxCargo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxHorario, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxSexo, javax.swing.GroupLayout.Alignment.LEADING, 0, 119, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtCancelar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTelef1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTelef2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldTelef3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDirecc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBoxHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtActualizar)
                    .addComponent(jbtCancelar))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jTextFieldBuscar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextFieldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarKeyTyped(evt);
            }
        });

        jbtBuscar.setBackground(new java.awt.Color(0, 0, 0));
        jbtBuscar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtBuscar.setForeground(java.awt.Color.white);
        jbtBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        jbtBuscar.setText("Buscar");
        jbtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscarActionPerformed(evt);
            }
        });

        jbtEditar.setBackground(new java.awt.Color(0, 0, 0));
        jbtEditar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtEditar.setForeground(new java.awt.Color(255, 255, 255));
        jbtEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        jbtEditar.setText("Editar");
        jbtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEditarActionPerformed(evt);
            }
        });

        jTableEmplead.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTableEmplead.setModel(Escritorio.MTE);
        jTableEmplead.getTableHeader().setResizingAllowed(false);
        jTableEmplead.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableEmplead);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jbtBuscar)
                .addGap(18, 18, 18)
                .addComponent(jbtEditar)
                .addGap(98, 98, 98))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtBuscar)
                    .addComponent(jbtEditar))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTelef1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelef1KeyTyped
        this.validar_llenado(evt, 1);
    }//GEN-LAST:event_jTextFieldTelef1KeyTyped

    private void jTextFieldTelef3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelef3KeyTyped
        this.validar_llenado(evt, 1);
    }//GEN-LAST:event_jTextFieldTelef3KeyTyped

    private void jTextFieldDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDniKeyTyped
        this.validar_llenado(evt, 1);
    }//GEN-LAST:event_jTextFieldDniKeyTyped

    private void jTextFieldNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyTyped
        this.validar_llenado(evt, 2);
    }//GEN-LAST:event_jTextFieldNombreKeyTyped

    private void jTextFieldTelef2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelef2KeyTyped
        this.validar_llenado(evt, 1);
    }//GEN-LAST:event_jTextFieldTelef2KeyTyped

    private void jTextFieldApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidoKeyTyped
        this.validar_llenado(evt, 2);
    }//GEN-LAST:event_jTextFieldApellidoKeyTyped

    private void jTextFieldBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarKeyTyped
        this.validar_llenado(evt, 2);
    }//GEN-LAST:event_jTextFieldBuscarKeyTyped

    private void jbtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscarActionPerformed
        boolean existe = false;
        String buscar = this.jTextFieldBuscar.getText().trim();
        if (buscar.equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese nombre del empleado!!", "Buscar Empleado", JOptionPane.WARNING_MESSAGE);
        } else {
            for (int i = 0; i < Escritorio.MTE.getRowCount(); i++) {
                if (Escritorio.MTE.getValueAt(i, 1).equals(buscar)) {
                    existe = true;
                    this.jTableEmplead.changeSelection(i, 1, false, false);
                    this.jTextFieldBuscar.setText("");
                }
            }
            if (existe == false) {
                JOptionPane.showMessageDialog(this, "El Nombre ingresado no existe.", "Buscar Empleado", JOptionPane.ERROR_MESSAGE);
                this.jTextFieldBuscar.setText("");
            }
        }
    }//GEN-LAST:event_jbtBuscarActionPerformed

    private void jbtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEditarActionPerformed
        int fila = this.jTableEmplead.getSelectedRow();
        if (fila != -1) {
            this.objE = Escritorio.MTE.getEmpleado(fila);
            this.cargarFormulario(objE);
            this.activar_controles(true);
            try {
                Escritorio.cargar_datos_Empleado();
            } catch (Exception ex) {
                Logger.getLogger(IFEditarEmplead.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No ha seleccionado un elemento de la tabla", "Editar Cliente", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbtEditarActionPerformed

    private void jbtActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtActualizarActionPerformed
        if (this.validar() == 0) {
            JOptionPane.showMessageDialog(this, "Porfavor!!!\nComplete todos los campos", "Validar Llenado", JOptionPane.WARNING_MESSAGE);
        } else {
            this.definirSexo_Telef();
            String user = this.objE.getUsuario();
            String contra = this.objE.getContraseña();
            Empleado objEmp = new Empleado(this.jTextFieldNombre.getText(),
                    this.jTextFieldApellido.getText(),
                    Integer.parseInt(this.jTextFieldDni.getText()),
                    this.telef,
                    this.jTextFieldDirecc.getText(),
                    this.sexo,
                    this.jComboBoxHorario.getSelectedItem().toString(),
                    this.jComboBoxCargo.getSelectedItem().toString(),
                    user,
                    contra);
            int id = this.objE.getCod_emp();
            objEmp.setCod_emp(id);
            try {
                EditarBD edit = new EditarBD();
                edit.editar_Empleado(objEmp);
                Escritorio.cargar_datos_Empleado();
                JOptionPane.showMessageDialog(null, "Edicción exitosa!!!\n", "Editar Empleado", JOptionPane.INFORMATION_MESSAGE);
                this.limpiar();
                this.activar_controles(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "OCURRIO UN ERROR: \n" + e.getMessage(), "Error BD", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbtActualizarActionPerformed

    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed
        this.limpiar();
        this.activar_controles(false);
    }//GEN-LAST:event_jbtCancelarActionPerformed

    private void jComboBoxHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxHorarioActionPerformed
        this.cargar_combo_cargo();
    }//GEN-LAST:event_jComboBoxHorarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxCargo;
    private javax.swing.JComboBox<String> jComboBoxHorario;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmplead;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextField jTextFieldDirecc;
    private javax.swing.JTextField jTextFieldDni;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelef1;
    private javax.swing.JTextField jTextFieldTelef2;
    private javax.swing.JTextField jTextFieldTelef3;
    private javax.swing.JButton jbtActualizar;
    private javax.swing.JButton jbtBuscar;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtEditar;
    // End of variables declaration//GEN-END:variables

    private void cargar_combo_cargo() {
        String obt = this.jComboBoxHorario.getSelectedItem().toString();
        switch (obt) {
            case "-Seleccione-":
                this.jComboBoxCargo.removeAllItems();
                this.jComboBoxCargo.addItem("-Seleccione-");
                this.jComboBoxCargo.addItem("Cajera");
                this.jComboBoxCargo.addItem("Mecánico");
                this.jComboBoxCargo.addItem("Vendedor");
                break;
            case "8hr":
                this.jComboBoxCargo.removeAllItems();
                this.jComboBoxCargo.addItem("-Seleccione-");
                this.jComboBoxCargo.addItem("Cajera");
                this.jComboBoxCargo.addItem("Mecánico");
                this.jComboBoxCargo.addItem("Vendedor");
                break;
            case "4hr":
                this.jComboBoxCargo.removeAllItems();
                this.jComboBoxCargo.addItem("-Seleccione-");
                this.jComboBoxCargo.addItem("Practicante");
                break;
            default: break;
        }
    }
    
    private int validar() {
        int lleno = 0;
        if (this.jTextFieldNombre.getText().trim().equals("")
                || this.jTextFieldApellido.getText().trim().equals("")
                || this.jTextFieldDni.getText().trim().equals("")
                || this.jTextFieldTelef1.getText().trim().equals("") || this.jTextFieldTelef1.getText().trim().length() < 3
                || this.jTextFieldTelef2.getText().trim().equals("") || this.jTextFieldTelef2.getText().trim().length() < 3
                || this.jTextFieldTelef3.getText().trim().equals("") || this.jTextFieldTelef3.getText().trim().length() < 3
                || this.jTextFieldDirecc.getText().trim().equals("")
                || this.jComboBoxSexo.getSelectedIndex() == 0
                || this.jComboBoxHorario.getSelectedIndex() == 0
                || this.jComboBoxCargo.getSelectedIndex() == 0) {

            return lleno;

        } else {
            lleno = 1;
        }
        return lleno;
    }

    private void limpiar() {
        this.jTextFieldNombre.setText("");
        this.jTextFieldApellido.setText("");
        this.jTextFieldDni.setText("");
        this.jTextFieldTelef1.setText("");
        this.jTextFieldTelef2.setText("");
        this.jTextFieldTelef3.setText("");
        this.jTextFieldDirecc.setText("");
        this.jComboBoxSexo.setSelectedIndex(0);
        this.jComboBoxHorario.setSelectedIndex(0);
        this.jComboBoxCargo.setSelectedIndex(0);

        this.sexo = "";
        this.telef = 0;
        this.objE = null;
    }

    private void validar_llenado(java.awt.event.KeyEvent evt, int opc) {
        //opc: 1 es para ingresar solo números
        //opc: 2 es para ingresar solo letras
        if (opc == 1) {
            char validar = evt.getKeyChar();
            if (Character.isLetter(validar)) {
                getToolkit().beep(); //sonido de alerta
                evt.consume();
            }
        }
        if (opc == 2) {
            char validar = evt.getKeyChar();
            if (Character.isDigit(validar)) {
                getToolkit().beep(); //sonido de alerta
                evt.consume();
            }
        }
    }

    private void validar_tamañoTexto() {
        this.jTextFieldNombre.setDocument(new Tamaño_TextField(this.jTextFieldNombre, 50));
        this.jTextFieldApellido.setDocument(new Tamaño_TextField(this.jTextFieldApellido, 50));
        this.jTextFieldDni.setDocument(new Tamaño_TextField(this.jTextFieldDni, 8));
        this.jTextFieldTelef1.setDocument(new Tamaño_TextField(this.jTextFieldTelef1, 3));
        this.jTextFieldTelef2.setDocument(new Tamaño_TextField(this.jTextFieldTelef2, 3));
        this.jTextFieldTelef3.setDocument(new Tamaño_TextField(this.jTextFieldTelef3, 3));
        this.jTextFieldDirecc.setDocument(new Tamaño_TextField(this.jTextFieldDirecc, 50));
        this.jTextFieldBuscar.setDocument(new Tamaño_TextField(this.jTextFieldBuscar, 50));
    }

    private void definirSexo_Telef() {
        String telef2 = this.jTextFieldTelef1.getText().trim();
        telef2 += this.jTextFieldTelef2.getText().trim();
        telef2 += this.jTextFieldTelef3.getText().trim();
        this.telef = Integer.parseInt(telef2);
        if (this.jComboBoxSexo.getSelectedIndex() == 1) {
            sexo = "F";
        } else {
            sexo = "M";
        }
    }

    private void definir_tamaño_columna() {
        TableColumnModel columnModel = this.jTableEmplead.getColumnModel();

        columnModel.getColumn(0).setPreferredWidth(300);
        columnModel.getColumn(1).setPreferredWidth(250);
        columnModel.getColumn(2).setPreferredWidth(100);
        columnModel.getColumn(3).setPreferredWidth(180);
        columnModel.getColumn(4).setPreferredWidth(200);
        columnModel.getColumn(5).setPreferredWidth(180);
    }

    private void activar_controles(boolean estado) {
        this.jTextFieldNombre.setEnabled(estado);
        this.jTextFieldApellido.setEnabled(estado);
        this.jTextFieldDni.setEnabled(estado);
        this.jTextFieldTelef1.setEnabled(estado);
        this.jTextFieldTelef2.setEnabled(estado);
        this.jTextFieldTelef3.setEnabled(estado);
        this.jTextFieldDirecc.setEnabled(estado);
        this.jComboBoxSexo.setEnabled(estado);
        this.jComboBoxHorario.setEnabled(estado);
        this.jComboBoxCargo.setEnabled(estado);
        this.jbtActualizar.setEnabled(estado);
        this.jbtCancelar.setEnabled(estado);

        this.jbtBuscar.setEnabled(!estado);
        this.jbtEditar.setEnabled(!estado);
        this.jTextFieldBuscar.setEnabled(!estado);
        this.jTableEmplead.setEnabled(!estado);
    }

    private void cargarFormulario(Empleado objE) {
        String sexo3 = "";
        if (objE.getSexo_emp().equals("F")) {
            sexo3 = "Femenino";
        } else {
            sexo3 = "Masculino";
        }
        String num = String.valueOf(objE.getTelef_emp());
        String telef1 = num.substring(0, 3);
        String telef2 = num.substring(3, 6);
        String telef3 = num.substring(6, 9);

        this.jTextFieldNombre.setText(objE.getNomb_emp());
        this.jTextFieldApellido.setText(objE.getApell_emp());
        this.jTextFieldDni.setText(String.valueOf(objE.getDni_emp()));
        this.jTextFieldTelef1.setText(telef1);
        this.jTextFieldTelef2.setText(telef2);
        this.jTextFieldTelef3.setText(telef3);
        this.jTextFieldDirecc.setText(objE.getDirec_emp());
        this.jComboBoxSexo.setSelectedItem(sexo3);
        if (objE.getCargo_emp().equals("Practicante")) {
            this.jComboBoxHorario.setSelectedItem("4hr");
        }else{
            this.jComboBoxHorario.setSelectedItem("8hr");
        }
        this.jComboBoxCargo.setSelectedItem(objE.getCargo_emp());
    }
}
