package Interfaces;

import Clases.*;
import Coneccion_BD.EditarBD;
import Modelo.Tamaño_TextField;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;

public class IFEditarProducto extends javax.swing.JInternalFrame {

    private Producto_Proveedor objPP = null;
    private Proveedor objP = null;
    private Marca objM = null;

    public IFEditarProducto() {
        initComponents();
        this.cargar_combos();
        this.validar_tamañoTexto();
        this.activar_controles(false);
        this.definir_tamaño_columna();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtActualizar = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jSpinnerPrecio = new javax.swing.JSpinner();
        jComboBoxProvee = new javax.swing.JComboBox<>();
        jTextFieldStock = new javax.swing.JTextField();
        jComboBoxMarca = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jbtBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProducProvee = new javax.swing.JTable();
        jbtEditar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Editar Producto");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jbtActualizar.setBackground(new java.awt.Color(0, 0, 0));
        jbtActualizar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtActualizar.setForeground(new java.awt.Color(255, 255, 255));
        jbtActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        jbtActualizar.setText("Actualizar");
        jbtActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtActualizarActionPerformed(evt);
            }
        });

        jbtCancelar.setBackground(java.awt.Color.red);
        jbtCancelar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jbtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        jbtCancelar.setText("Cancelar");
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Código:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descripción:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Stock:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Precio:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Marca:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Proveedor:");

        jTextFieldCodigo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jTextFieldNombre.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jSpinnerPrecio.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jComboBoxProvee.setBackground(new java.awt.Color(0, 0, 51));
        jComboBoxProvee.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jComboBoxProvee.setForeground(new java.awt.Color(255, 255, 255));

        jTextFieldStock.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextFieldStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldStockKeyTyped(evt);
            }
        });

        jComboBoxMarca.setBackground(new java.awt.Color(0, 0, 51));
        jComboBoxMarca.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jComboBoxMarca.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxProvee, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldStock, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSpinnerPrecio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                            .addComponent(jComboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtCancelar)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinnerPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxProvee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtActualizar)
                    .addComponent(jbtCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jTextFieldBuscar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jbtBuscar.setBackground(new java.awt.Color(0, 0, 0));
        jbtBuscar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jbtBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        jbtBuscar.setText("Buscar");
        jbtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscarActionPerformed(evt);
            }
        });

        jTableProducProvee.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTableProducProvee.setModel(Escritorio.MTPP);
        jTableProducProvee.getTableHeader().setResizingAllowed(false);
        jTableProducProvee.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableProducProvee);

        jbtEditar.setBackground(new java.awt.Color(0, 0, 0));
        jbtEditar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtEditar.setForeground(new java.awt.Color(255, 255, 255));
        jbtEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        jbtEditar.setText("Editar");
        jbtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtBuscar)
                .addGap(18, 18, 18)
                .addComponent(jbtEditar)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtBuscar)
                    .addComponent(jbtEditar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtActualizarActionPerformed
        if (this.validar() == 0) {
            JOptionPane.showMessageDialog(this, "Porfavor!!!\nComplete todos los campos", "Validar Llenado", JOptionPane.WARNING_MESSAGE);
        } else {
            this.validar_Marca_Provee();
            Producto_Proveedor objPPr = new Producto_Proveedor(
                    this.objP,
                    new Producto(this.jTextFieldCodigo.getText(),
                            this.jTextFieldNombre.getText(), Integer.parseInt(this.jTextFieldStock.getText()),
                            Float.parseFloat(this.jSpinnerPrecio.getValue().toString()),
                            this.objM));
            int id = this.objPP.getCod_produx();
            int id_produc = this.objPP.getId_pord().getCod_prod();
            objPPr.setCod_produx(id);
            objPPr.getId_pord().setCod_prod(id_produc);
            try {
                EditarBD edit = new EditarBD();
                edit.editar_Produc_Provee(objPPr);
                Escritorio.cargar_datos_Producto();
                JOptionPane.showMessageDialog(null, "Inserción exitosa!!!\n", "Inserción", JOptionPane.INFORMATION_MESSAGE);
                this.limpiar();
                this.activar_controles(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "OCURRIO UN ERROR: \n" + e.getMessage(), "Error BD", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbtActualizarActionPerformed

    private void jbtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscarActionPerformed
        boolean existe = false;
        String buscar = this.jTextFieldBuscar.getText().trim();
        if (buscar.equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese el código a buscar!!", "Buscar Producto", JOptionPane.WARNING_MESSAGE);
        } else {
            for (int i = 0; i < Escritorio.MTPP.getRowCount(); i++) {
                if (Escritorio.MTPP.getValueAt(i, 0).equals(buscar)) {
                    existe = true;
                    this.jTableProducProvee.changeSelection(i, 1, false, false);
                    this.jTextFieldBuscar.setText("");
                }
            }
            if (existe == false) {
                JOptionPane.showMessageDialog(this, "Código ingresado no existente.", "Buscar Producto", JOptionPane.INFORMATION_MESSAGE);
                this.jTextFieldBuscar.setText("");
            }
        }
    }//GEN-LAST:event_jbtBuscarActionPerformed

    private void jbtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEditarActionPerformed
        int fila = this.jTableProducProvee.getSelectedRow();
        if (fila != -1) {
            this.objPP = Escritorio.MTPP.getProdPorevee(fila);
            this.cargarFormulario(objPP);
            this.activar_controles(true);
            Escritorio.cargar_datos_Producto();
        } else {
            JOptionPane.showMessageDialog(this, "No ha seleccionado un elemento de la tabla", "Editar Cliente", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbtEditarActionPerformed

    private void jTextFieldStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldStockKeyTyped
        this.validar_llenado(evt);
    }//GEN-LAST:event_jTextFieldStockKeyTyped

    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed
        this.limpiar();
        this.activar_controles(false);
    }//GEN-LAST:event_jbtCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Marca> jComboBoxMarca;
    private javax.swing.JComboBox<Proveedor> jComboBoxProvee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerPrecio;
    private javax.swing.JTable jTableProducProvee;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldStock;
    private javax.swing.JButton jbtActualizar;
    private javax.swing.JButton jbtBuscar;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtEditar;
    // End of variables declaration//GEN-END:variables

    private void cargar_combos() {
        this.jComboBoxMarca.removeAllItems();
        this.jComboBoxProvee.removeAllItems();
        //Cargar combo Marca
        Marca objM = new Marca();
        objM.setNomb_mar("-Seleccione-");
        this.jComboBoxMarca.addItem(objM);
        try {
            objM.mostrar_Marca(this.jComboBoxMarca);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR!!!\n" + e.getMessage(), "Error BD", JOptionPane.ERROR_MESSAGE);
        }
        //Cargar combo Proveedor
        Proveedor objP = new Proveedor();
        objP.setNomb_provee("-Seleccione-");
        this.jComboBoxProvee.addItem(objP);
        try {
            objP.mostrar_Proveedor(this.jComboBoxProvee);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR!!!\n" + e.getMessage(), "Error BD", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void validar_llenado(java.awt.event.KeyEvent evt) {
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
        }
    }

    private int validar() {
        int lleno = 0;
        if (this.jTextFieldNombre.getText().trim().equals("")
                || this.jTextFieldStock.getText().trim().equals("")
                || this.jTextFieldCodigo.getText().trim().equals("")
                || this.jSpinnerPrecio.getValue().toString().equals("0")
                || this.jComboBoxMarca.getSelectedIndex() == 0
                || this.jComboBoxProvee.getSelectedIndex() == 0) {
            return lleno;
        } else {
            lleno = 1;
        }
        return lleno;
    }

    private void limpiar() {
        this.jTextFieldNombre.setText("");
        this.jTextFieldStock.setText("");
        this.jTextFieldCodigo.setText("");
        this.jSpinnerPrecio.setValue(0);
        this.jComboBoxMarca.setSelectedIndex(0);
        this.jComboBoxProvee.setSelectedIndex(0);

        this.objPP = null;
        this.objM = null;
        this.objP = null;
    }

    private void validar_tamañoTexto() {
        this.jTextFieldCodigo.setDocument(new Tamaño_TextField(this.jTextFieldCodigo, 20));
        this.jTextFieldNombre.setDocument(new Tamaño_TextField(this.jTextFieldNombre, 50));
        this.jTextFieldStock.setDocument(new Tamaño_TextField(this.jTextFieldStock, 3));
    }

    private void activar_controles(boolean estado) {
        this.jTextFieldCodigo.setEnabled(estado);
        this.jTextFieldNombre.setEnabled(estado);
        this.jTextFieldStock.setEnabled(estado);
        this.jSpinnerPrecio.setEnabled(estado);
        this.jComboBoxMarca.setEnabled(estado);
        this.jComboBoxProvee.setEnabled(estado);
        this.jbtActualizar.setEnabled(estado);
        this.jbtCancelar.setEnabled(estado);

        this.jTextFieldBuscar.setEnabled(!estado);
        this.jbtBuscar.setEnabled(!estado);
        this.jbtEditar.setEnabled(!estado);
        this.jTableProducProvee.setEnabled(!estado);
    }

    private void cargarFormulario(Producto_Proveedor objPP) {
        this.objM = objPP.getId_pord().getId_mar();
        this.objP = objPP.getId_prov();

        this.jTextFieldCodigo.setText(objPP.getId_pord().getCode());
        this.jTextFieldNombre.setText(objPP.getId_pord().getNomb_prod());
        this.jTextFieldStock.setText(String.valueOf(objPP.getId_pord().getStock_prod()));
        this.jSpinnerPrecio.setValue(objPP.getId_pord().getPrecio_prod());
        this.jComboBoxMarca.getModel().setSelectedItem(this.objM);
        this.jComboBoxProvee.getModel().setSelectedItem(this.objP);
    }

    private void definir_tamaño_columna() {
        TableColumnModel columnModel = this.jTableProducProvee.getColumnModel();

        columnModel.getColumn(0).setPreferredWidth(150);
        columnModel.getColumn(1).setPreferredWidth(400);
        columnModel.getColumn(2).setPreferredWidth(100);
        columnModel.getColumn(3).setPreferredWidth(90);
        columnModel.getColumn(4).setPreferredWidth(300);
    }

    private void validar_Marca_Provee() {
        if (this.jComboBoxProvee.getItemAt(this.jComboBoxProvee.getSelectedIndex()) != null) {
            this.objP = this.jComboBoxProvee.getItemAt(this.jComboBoxProvee.getSelectedIndex());
        }
        if (this.jComboBoxMarca.getItemAt(this.jComboBoxMarca.getSelectedIndex()) != null) {
            this.objM = this.jComboBoxMarca.getItemAt(this.jComboBoxMarca.getSelectedIndex());
        }
    }
}
