package Interfaces;

import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;

public class IFListaCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFReporteCliente
     */
    public IFListaCliente() {
        initComponents();
        this.tamanio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jTextFieldBuscar = new javax.swing.JTextField();
        jbtBuscar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setIconifiable(true);
        setTitle("Listado de Clientes");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jTableCliente.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTableCliente.setModel(Escritorio.MTC);
        jTableCliente.getTableHeader().setResizingAllowed(false);
        jTableCliente.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableCliente);

        jTextFieldBuscar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextFieldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarKeyTyped(evt);
            }
        });

        jbtBuscar.setBackground(new java.awt.Color(0, 0, 0));
        jbtBuscar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jbtBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jbtBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        jbtBuscar.setText("Buscar");
        jbtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 100, Short.MAX_VALUE)
                        .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jbtBuscar)
                        .addGap(102, 102, 102)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep(); //sonido de alerta
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldBuscarKeyTyped

    private void jbtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscarActionPerformed
        boolean existe = false;
        String buscar = this.jTextFieldBuscar.getText().trim();
        if (buscar.equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese DNI del cliente a buscar!!", "Buscar Cliente", JOptionPane.WARNING_MESSAGE);
        } else {
            for (int i = 0; i < Escritorio.MTC.getRowCount(); i++) {
                if (Escritorio.MTC.getValueAt(i, 3).equals(buscar)) {
                    existe = true;
                    this.jTableCliente.changeSelection(i, 1, false, false);
                    this.jTextFieldBuscar.setText("");
                }
            }
            if (existe == false) {
                JOptionPane.showMessageDialog(this, "El DNI ingresado no existe.", "Buscar Cliente", JOptionPane.INFORMATION_MESSAGE);
                this.jTextFieldBuscar.setText("");
            }
        }
    }//GEN-LAST:event_jbtBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JButton jbtBuscar;
    // End of variables declaration//GEN-END:variables
    
    public void tamanio() {
        TableColumnModel columnModel = this.jTableCliente.getColumnModel();

        columnModel.getColumn(0).setPreferredWidth(250);
        columnModel.getColumn(1).setPreferredWidth(250);
        columnModel.getColumn(2).setPreferredWidth(100);
        columnModel.getColumn(3).setPreferredWidth(180);
        columnModel.getColumn(4).setPreferredWidth(180);
        columnModel.getColumn(5).setPreferredWidth(400);
    }
}
