package Interfaces;

import Clases.Cliente;
import Coneccion_BD.InsertarBD;
import Modelo.Tamaño_TextField;
import javax.swing.JOptionPane;

public class IFRegistroCliente extends javax.swing.JInternalFrame {

    int telef = 0; String sexo="";
    public IFRegistroCliente() {
        initComponents();
        this.validar_tamañoTexto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDni = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTelef1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldTelef2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldTelef3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDirecc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jbtGuardar = new javax.swing.JButton();
        jbtcanCancelar = new javax.swing.JButton();
        jbtSalir = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Registro Cliente");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Nombres:");

        jTextFieldNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Apellidos:");

        jTextFieldApellido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldApellidoKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("DNI:");

        jTextFieldDni.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDniKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Teléfono:");

        jTextFieldTelef1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldTelef1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelef1KeyTyped(evt);
            }
        });

        jLabel9.setText("-");

        jTextFieldTelef2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldTelef2.setToolTipText("");
        jTextFieldTelef2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelef2KeyTyped(evt);
            }
        });

        jLabel10.setText("-");

        jTextFieldTelef3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldTelef3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelef3KeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Dirección:");

        jTextFieldDirecc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Sexo:");

        jComboBoxSexo.setBackground(new java.awt.Color(0, 0, 102));
        jComboBoxSexo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jComboBoxSexo.setForeground(java.awt.Color.white);
        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-", "Femenino", "Masculino" }));

        jbtGuardar.setBackground(new java.awt.Color(0, 0, 0));
        jbtGuardar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtGuardar.setForeground(java.awt.Color.white);
        jbtGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardaa.png"))); // NOI18N
        jbtGuardar.setText("Guardar");
        jbtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGuardarActionPerformed(evt);
            }
        });

        jbtcanCancelar.setBackground(java.awt.Color.red);
        jbtcanCancelar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtcanCancelar.setForeground(java.awt.Color.white);
        jbtcanCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        jbtcanCancelar.setText("Cancelar");
        jbtcanCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtcanCancelarActionPerformed(evt);
            }
        });

        jbtSalir.setBackground(new java.awt.Color(0, 0, 0));
        jbtSalir.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbtSalir.setForeground(java.awt.Color.white);
        jbtSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida-de-emergencia.png"))); // NOI18N
        jbtSalir.setText("Salir");
        jbtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTelef1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTelef2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTelef3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldDni)
                                    .addComponent(jTextFieldApellido)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldDirecc)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(86, 86, 86))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtcanCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtSalir)
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldTelef1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldTelef2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldTelef3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldDirecc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtGuardar)
                    .addComponent(jbtcanCancelar)
                    .addComponent(jbtSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTelef2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelef2KeyTyped
        this.validar_llenado(evt, 1);
    }//GEN-LAST:event_jTextFieldTelef2KeyTyped

    private void jTextFieldTelef3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelef3KeyTyped
        this.validar_llenado(evt, 1);
    }//GEN-LAST:event_jTextFieldTelef3KeyTyped

    private void jTextFieldNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyTyped
        this.validar_llenado(evt, 2);
    }//GEN-LAST:event_jTextFieldNombreKeyTyped

    private void jTextFieldApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidoKeyTyped
        this.validar_llenado(evt, 2);
    }//GEN-LAST:event_jTextFieldApellidoKeyTyped

    private void jTextFieldDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDniKeyTyped
        this.validar_llenado(evt, 1);
    }//GEN-LAST:event_jTextFieldDniKeyTyped

    private void jTextFieldTelef1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelef1KeyTyped
        this.validar_llenado(evt, 1);
    }//GEN-LAST:event_jTextFieldTelef1KeyTyped

    private void jbtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGuardarActionPerformed
        if (this.validar() == 0) {
            JOptionPane.showMessageDialog(this, "Porfavor!!!\nComplete todos los campos correctamente", "Validar Llenado", JOptionPane.WARNING_MESSAGE);
        }else{
            this.definirSexo_Telef();
            Cliente objC = new Cliente(this.jTextFieldNombre.getText(),
                                       this.jTextFieldApellido.getText(),
                                       String.valueOf(this.telef),
                                       this.jTextFieldDni.getText(),
                                       this.sexo,
                                       this.jTextFieldDirecc.getText());
            try {
                InsertarBD ins = new InsertarBD();
                ins.agregar_Cliente(objC);
                Escritorio.cargar_datos_Cliente();
                JOptionPane.showMessageDialog(null, "Inserción exitosa!!!\n", "Inserción", JOptionPane.INFORMATION_MESSAGE);
                this.limpiar();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "OCURRIO UN ERROR: \n" + e.getMessage(), "Error BD", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbtGuardarActionPerformed

    private void jbtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtSalirActionPerformed

    private void jbtcanCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtcanCancelarActionPerformed
        this.limpiar();
    }//GEN-LAST:event_jbtcanCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldDirecc;
    private javax.swing.JTextField jTextFieldDni;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelef1;
    private javax.swing.JTextField jTextFieldTelef2;
    private javax.swing.JTextField jTextFieldTelef3;
    private javax.swing.JButton jbtGuardar;
    private javax.swing.JButton jbtSalir;
    private javax.swing.JButton jbtcanCancelar;
    // End of variables declaration//GEN-END:variables

    private void validar_llenado(java.awt.event.KeyEvent evt, int opc) {
        //opc: 1 es para ingresar solo números
        //opc: 2 es para ingresar solo letras
        if (opc == 1) {
            char validar = evt.getKeyChar();
            if (Character.isLetter(validar)) {
                getToolkit().beep(); //sonido de alerta
                evt.consume();
            }
        }
        if (opc == 2) {
            char validar = evt.getKeyChar();
            if (Character.isDigit(validar)) {
                getToolkit().beep(); //sonido de alerta
                evt.consume();
            }
        }
    }
    
    private int validar() {
        int lleno = 0;
        if (this.jTextFieldNombre.getText().trim().equals("")
                || this.jTextFieldApellido.getText().trim().equals("")
                || this.jTextFieldDni.getText().trim().equals("")
                || this.jTextFieldTelef1.getText().trim().equals("") || this.jTextFieldTelef1.getText().trim().length() < 3
                || this.jTextFieldTelef2.getText().trim().equals("") || this.jTextFieldTelef2.getText().trim().length() < 3
                || this.jTextFieldTelef3.getText().trim().equals("") || this.jTextFieldTelef3.getText().trim().length() < 3
                || this.jTextFieldDirecc.getText().trim().equals("")
                || this.jComboBoxSexo.getSelectedIndex() == 0) {
            return lleno;

        } else {
            lleno = 1;
        }
        return lleno;
    }
    private void definirSexo_Telef() {
        String telef = this.jTextFieldTelef1.getText().trim();
        telef += this.jTextFieldTelef2.getText().trim();
        telef += this.jTextFieldTelef3.getText().trim();
        this.telef = Integer.parseInt(telef);
        if (this.jComboBoxSexo.getSelectedIndex() == 1) {
            sexo = "F";
        } else {
            sexo = "M";
        }
    }
    private void limpiar() {
        this.jTextFieldNombre.setText("");
        this.jTextFieldApellido.setText("");
        this.jTextFieldDni.setText("");
        this.jTextFieldTelef1.setText("");
        this.jTextFieldTelef2.setText("");
        this.jTextFieldTelef3.setText("");
        this.jTextFieldDirecc.setText("");
        this.jComboBoxSexo.setSelectedIndex(0);

        this.sexo = "";
        this.telef = 0;
    }
    private void validar_tamañoTexto() {
        this.jTextFieldNombre.setDocument(new Tamaño_TextField(this.jTextFieldNombre, 50));
        this.jTextFieldApellido.setDocument(new Tamaño_TextField(this.jTextFieldApellido, 50));
        this.jTextFieldDni.setDocument(new Tamaño_TextField(this.jTextFieldDni, 8));
        this.jTextFieldTelef1.setDocument(new Tamaño_TextField(this.jTextFieldTelef1, 3));
        this.jTextFieldTelef2.setDocument(new Tamaño_TextField(this.jTextFieldTelef2, 3));
        this.jTextFieldTelef3.setDocument(new Tamaño_TextField(this.jTextFieldTelef3, 3));
        this.jTextFieldDirecc.setDocument(new Tamaño_TextField(this.jTextFieldDirecc, 50));
    }
}
